# Demyx
# https://demyx.sh

notifications:
  email:
    on_success: never
    on_failure: always

services:
  - docker

env:
  - DEMYX_USERNAME=demyx DEMYX_REPOSITORY=openlitespeed

before_install:
  - docker pull debian:buster-slim
  - docker pull demyx/mariadb
  - docker pull demyx/wordpress:cli
  - docker pull demyx/utilities
  - docker network create demyx

script:
  # tag-latest test
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY" tag-latest
  - docker run -d --name=demyx_db --network=demyx -e MARIADB_DATABASE=demyx -e MARIADB_USERNAME=demyx -e MARIADB_PASSWORD=demyx -e MARIADB_ROOT_PASSWORD=demyx demyx/mariadb
  - docker run -d --name=demyx_wp --network=demyx -v demyx_wp:/demyx -e WORDPRESS_DB_HOST=demyx_db -e WORDPRESS_DB_NAME=demyx -e WORDPRESS_DB_USER=demyx -e WORDPRESS_DB_PASSWORD=demyx demyx/"$DEMYX_REPOSITORY"
  - sleep 5
  - docker run --network=demyx --volumes-from=demyx_wp --workdir=/demyx demyx/wordpress:cli config create --dbhost=demyx_db --dbname=demyx --dbuser=demyx --dbpass=demyx
  - docker run --network=demyx --volumes-from=demyx_wp --workdir=/demyx demyx/wordpress:cli core install --url=http://localhost --title=demyx --admin_user=demyx --admin_password=demyx --admin_email=info@domain.tld --skip-email
  - docker exec demyx_wp sh -c "wget -qO- http://localhost | grep 'Hello world'"
  # tag-bedrock test
  - docker build --no-cache -t demyx/"$DEMYX_REPOSITORY":bedrock tag-bedrock
  - docker run -d --name=demyx_db_bedrock --network=demyx -e MARIADB_DATABASE=demyx -e MARIADB_USERNAME=demyx -e MARIADB_PASSWORD=demyx -e MARIADB_ROOT_PASSWORD=demyx demyx/mariadb
  - docker run -d --name=demyx_wp_bedrock --network=demyx -v demyx_wp_bedrock:/demyx -e WORDPRESS_DB_HOST=demyx_db_bedrock -e WORDPRESS_DB_NAME=demyx -e WORDPRESS_DB_USER=demyx -e WORDPRESS_DB_PASSWORD=demyx demyx/"$DEMYX_REPOSITORY":bedrock
  - sleep 5
  - docker run --network=demyx -v demyx_wp_bedrock:/demyx demyx/wordpress:cli core install --url=http://localhost --title=demyx --admin_user=demyx --admin_password=demyx --admin_email=info@domain.tld --skip-email
  - docker exec demyx_wp_bedrock sh -c "wget -qO- http://localhost | grep 'Hello world'"

after_success:
  - echo "$DEMYX_PASSWORD" | docker login -u "$DEMYX_USERNAME" --password-stdin
  - docker push demyx/"$DEMYX_REPOSITORY"
  - docker push demyx/"$DEMYX_REPOSITORY":bedrock
  - bash travis.sh
